### ISSUE TITLE
NullReferenceException from Phoenix.Interfaces.Response.Dispose()

### ISSUE THREAD

**Issue by dwdii** [Azure/hdinsight-phoenix-sharp#12]
My situation is that one of my region servers is down but my PQS is up. I'm using VNET mode. I can successfully connect via the OpenConnectionRequestAsync call followed by successful ConnectionSyncRequestAsync and CreateStatementRequestAsync calls. But when I then execute a PrepareAndExecuteRequestAsync, I get a NullReferenceException.  

Here is my stack trace:

```
   at PhoenixSharp.Interfaces.Response.Dispose()
   at PhoenixSharp.PhoenixClient.<PrepareAndExecuteRequestAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Garuda.Data.PhoenixConnection.<InternalExecuteRequestAsync>d__46.MoveNext() in C:\Code\DotNet\GarudaUtil\Garuda.Data\PhoenixConnection.cs:line 317
```

The issue appears to be an unchecked forwarding of the Dispose to the WebResponse in the [Phoenix.Interfaces.Response class's](https://github.com/Azure/hdinsight-phoenix-sharp/blob/master/PhoenixSharp.Interfaces/IWebRequester.cs) Dispose method. 

In my case the VnetWebRequester is getting a "operation timed out" WebException, and the WebResponse object passed into the Phoenix.Interfaces.Response.WebResponse property is null (in the WebException catch block).

This appears to result in a null reference exception from the following line of PhoenixClient::PrepareAndExecuteBatchRequestAsync: 

```
if (webResponse.WebResponse.StatusCode != HttpStatusCode.OK)
```

Which then throws through the `using` statement causing the Dispose related NullReferenceException. 

```
        public void Dispose()
        {
            if (PostRequestAction != null)
            {
                PostRequestAction(this);
            }
            WebResponse.Dispose(); // <-- 
        }
```

The `if (webResponse.WebResponse.StatusCode != HttpStatusCode.OK)` line is listed in many of the PhoenixClient methods, so this issue looks like it could appear in one form or another for other calls with a timeout related response.

**Comment by duoxu** [comment]
@dwdii 

Thanks for reporting this bug. On last Friday, one of our customers pointed out the same bug in our .NET HBase SDK and provided a fix. I will port that fix to Phoenix SDK, too.

When I shut down all the regionservers, I can repro this bug in my unit test. Basically as you said, our WebRequester receives a timeout exception due to unresponsive regionservers.

The fix will also fix another issue in our webrequester that 

HttpWebRequest.Timeout is not honored for Async calls on the HttpWebRequest. So calls to async calls need to timeout explicitly and abort the webrequest. 

Thanks @ajithg-msft for the fix and I will port the fix to our Phoenix SDK which also uses HttpWebRequest.

After that fix, RequestOptions.TimeoutMillis will be honored in async calls and it will throw timeout exceptions instead of throwing NullReferenceException.

**Comment by duoxu** [comment]
I looked at the code again, actually, the errors returned by Phoenix Query Server (HTTP 500) need to be decoded and returned as WebResponse. The timeout exception is not handled. I think we need to handle this timeout exception differently.

I think I know the issue now and will give a fix.

**Comment by duoxu** [comment]
@dwdii 
I have checked in a fix. Please try it out. The default 30s timeout setting will be honored and on client side you should get a timeout exception instead of NullReferenceException.

**Comment by dwdii** [comment]
Thanks @duoxu  - I tested with your new fix and it works well in my scenario. When my hbase master was down, I received a System.TimeoutException as you mentioned. I also tested my suite of unit tests with my hbase master up and they all passed without issue. Thanks again!
